sudo: required

matrix:
  include:
    ###################
    - language: cpp
      compiler: clang
      os: linux
      script: ./configure

deploy:
  provider: releases
  api_key: "SVXTd+eS0BdHDrSj3rf/0iS8eLWb7fLMBTGVXrwk0WKeL53lBodP4x2o/xjRgNYXEXmf26pNtGpyhI2l0Tc/K9iXzYCEPlaVhdbCMTnqMWGkZERlb8dWsGUTWoojk92AllE0cq87UUDKYM32C/gMDwTuB1eyZ3Yh9AnbzWIX4fAuVtFl0tOpC2BbWdV+fKSQp76xFNFcVsQILrCAbEwZsNjAVwSceAQMcymyLfujuJxMJIJ2yPMerf4hSlZMYddVp1XiqCwjK4GMFAMMjAvCLdo+BpS0IPMGIKU5xy9zhW4Uz82CL/71ybcwqiV4xaZbgfdRHttwd/JCL4tVkrRn5o7qiYGv/zzi7pdXgGVUIKbchDgRyyAW4omy9eHksufNcZ/g4vn6UTxuZVF4oO4DvB9n/1BuqC5i9lvh8kRlBy7GcSNMWa0C/S8uBKTEJcfDiC5HQ5sxNV1cFe6NOzIknVC62z5KIRcqrmRCrQLk/rmDfWhcN3mkXUgKuhKSeYgWYJIUZMAfxj6tnMaQ7vLu1tdwTuKEPGXbkZ792sgHt4lRPv6LS3bf4rqZUyhiIvNxHJ0wAK9mDD5BhOigvp6vNePUDdhEPQ1i3dUBWbdqTDlf1bE89RTQyvU8gUHGscDlJAGOYzxDJtuZsZPMMy9TJm4d4uEZPjTZ61oyi/rdiS0="
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true