sudo: required
matrix:
  include:
  - language: cpp
    compiler: clang
    os: linux
    script: "./configure"
deploy:
  provider: releases
  api_key:
    secure: 6qDEulpsaIXJ8MQbdzrFaUhRvhc2gYvCsVM2WF77rBijBMee1RFn7La+Z2KQs4LSIsTvLlu6IItw2hk8lyDsZ+rZeiMw9ktitTzJvbOs89EneMedY+DwgoXiUYmpG86dTQkfDLJsf9+mntC6xDtFJheOm8MCZk1mIsy8nXjtBixLyBN0izBp0+heWT5lK8RwFu03AIQDsQBBRTM/QqKDf6T3smhG76H4JINXEYmRT2fN1Yt62+uoMdezNc0lV3rjTBdHgC/fFDQaQxYJZX9Hckqpy2FoUpNsh+zmTQcp5o8YSlstEzTn6U1NphGXM1Y3/Np6wFXJsj41wazXh4EFkeTUZu7Oeer0zgPNicew94KJLQbhCmEHbKbZj8TtMGADWOjTqvCkhRYoc4c2bq7PuHrzlyd6qALHkdiiRuqANBMeC86px5yBSCy99vcrsPYl0jX7/qiWkxCswDMNkgOVvhhQBtGCuJOmfnOT4sq06V73RtPN/oru/P4WMbKr5KS1ZshPRlZqNPOk762wQpykW0i9Knj6106i+0LBhbuwdCofH8kTpclgVZupBZQxzOKeflAMw2rl/uDvKGEpKDNysD24QGbJR2yTin/su7G/gKSehR813zdNBkfKXlwN7K/TyWOR/dT3zQRmpke0M/lWfxGgDbHtsSVGl561+5Hr7ms=
  file: "./build.zip"
  on:
    repo: ShuangLiu1992/test_ci
  skip_cleanup: 'true'
